### ISSUE TITLE
Fallback to GitHub?

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-content-proxy#20]
In `helix-pipeline`, requesting a non-existing item in Word/GDocs will result in another request to GitHub.

In `helix-content-proxy`, you just get a 404.

Additionally, there is a suggestion for `helix-pipeline` to only served Word/GDocs if the file does not exist in GitHub. https://github.com/adobe/helix-pipeline/issues/726

Between the three options:

1. GitHub should override Word
2. Word should override GitHub
3. There are no overrides at all

One is clearly the best. I just don't know which one.

**Comment by tripodsan** [comment]
well, in adobe/helix-pipeline#726, the idea would be that we try to load from github first, since it's the cheapest, and only after that from the externals.

but with the content-proxy, I assume that we only have 1 request to fastly to load the content.
so in this case, fastly, or at least the content-proxy should implement the fallback.

I would go for (1), but make it blocking.....

@davidnuescheler WDYT?

**Comment by trieloff** [comment]
See #32 for the resolution: we won't have any implicit default fallbacks, all fallbacks must be explicit
